version: '3.4'

services:

  django:
    container_name: local_dev_django
    image: baseimage
    build:
      context: ../
      dockerfile: ./docker/baseimage/Dockerfile
    env_file:
     - ../container_environments/test-stack.yaml
    working_dir: /src
    volumes:
      - ../:/src
    ports:
      - "8000:8000"
    links:
      - postgres
      - rabbitmq
      - redis
    command: bash -c "./docker/scripts/initialize-webapp-dev.sh"

  celery:
    container_name: local_dev_celery
    image: baseimage
    build:
      context: ../
      dockerfile: ./docker/baseimage/Dockerfile
    env_file:
     - ../container_environments/test-stack.yaml
    working_dir: /src
    volumes:
      - ../:/src
    links:
      - postgres
      - rabbitmq
      - redis
    command: bash -c "./docker/scripts/start-celery-worker.sh"

  redis:
    image: redis
    container_name: local_dev_redis
    env_file:
     - ../container_environments/test-stack.yaml

  rabbitmq:
    image: rabbitmq:3.6
    container_name: local_dev_rabbitmq
    env_file:
     - ../container_environments/test-stack.yaml

  postgres:
    image: postgres:9.4
    container_name: local_dev_postgres
    env_file:
     - ../container_environments/test-stack.yaml
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: false